version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: ["zookeeper"]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes: ["kafka-data:/var/lib/kafka/data"]

  eureka:
    build: ./eureka-server
    ports: ["8761:8761"]
    depends_on: ["kafka"]

  gateway:
    build: ./gateway-service
    ports: ["8080:8080"]
    depends_on: ["eureka"]

  client-service:
    build: ./client-service
    ports: ["8084:8084"]
    depends_on: ["eureka"]

  vehicle-service:
    build: ./vehicle-service
    ports: ["8085:8085"]
    depends_on: ["eureka","kafka"]

  rental-service:
    build: ./rental-service
    ports: ["8086:8086"]
    depends_on: ["eureka","kafka"]

volumes:
  kafka-data:
